# -*- coding: utf-8 -*-
"""forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoOXZh-26BCaBT4U_lwdAv5TglNQdLIZ
"""

!pip install Streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

from datetime import timedelta


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="PJM Energy Forecast",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown(
    """
    <style>

    /* -------------------------------------------------------
       IMPORT FONT
    ------------------------------------------------------- */

    @import url(
        'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap'
    );

    html, body, [class*="css"] {
        font-family: 'Inter', sans-serif;
    }


    /* -------------------------------------------------------
       MAIN APP BACKGROUND
    ------------------------------------------------------- */

    .stApp {
        background:
            linear-gradient(
                rgba(3, 12, 28, 0.93),
                rgba(3, 12, 28, 0.96)
            ),
            url("https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=2400&q=85");

        background-size: cover;
        background-position: center;
        background-attachment: fixed;
    }


    /* -------------------------------------------------------
       MAIN CONTENT
    ------------------------------------------------------- */

    .block-container {
        padding-top: 2rem;
        padding-bottom: 3rem;
        max-width: 1400px;
    }


    /* -------------------------------------------------------
       SIDEBAR
    ------------------------------------------------------- */

    section[data-testid="stSidebar"] {
        background:
            linear-gradient(
                180deg,
                rgba(5, 17, 38, 0.98),
                rgba(8, 26, 53, 0.98)
            );

        border-right: 1px solid rgba(255,255,255,0.08);
    }

    section[data-testid="stSidebar"] * {
        color: #e8f1ff !important;
    }


    /* -------------------------------------------------------
       HERO HEADER
    ------------------------------------------------------- */

    .hero {
        padding: 35px 35px 30px 35px;

        border-radius: 24px;

        background:
            linear-gradient(
                135deg,
                rgba(0, 174, 255, 0.20),
                rgba(6, 27, 62, 0.85)
            );

        border: 1px solid rgba(122, 208, 255, 0.20);

        box-shadow:
            0 20px 50px rgba(0,0,0,0.30);

        margin-bottom: 25px;
    }


    .hero-title {
        font-size: 42px;
        font-weight: 800;

        color: white;

        margin-bottom: 8px;

        letter-spacing: -1.5px;
    }


    .hero-subtitle {
        color: #b9d5f7;

        font-size: 17px;

        line-height: 1.6;
    }


    .hero-badge {
        display: inline-block;

        padding: 7px 14px;

        margin-bottom: 15px;

        border-radius: 50px;

        background: rgba(0, 196, 255, 0.14);

        border: 1px solid rgba(0, 196, 255, 0.25);

        color: #71ddff;

        font-size: 13px;

        font-weight: 700;

        letter-spacing: 0.8px;
    }


    /* -------------------------------------------------------
       CARDS
    ------------------------------------------------------- */

    .metric-card {

        padding: 22px;

        border-radius: 18px;

        background:
            linear-gradient(
                145deg,
                rgba(12, 36, 70, 0.93),
                rgba(7, 20, 43, 0.93)
            );

        border:
            1px solid rgba(120, 185, 255, 0.14);

        box-shadow:
            0 15px 35px rgba(0,0,0,0.18);

        min-height: 125px;
    }


    .metric-label {

        color: #90b0d4;

        font-size: 13px;

        font-weight: 600;

        text-transform: uppercase;

        letter-spacing: 1px;

        margin-bottom: 9px;
    }


    .metric-value {

        color: white;

        font-size: 27px;

        font-weight: 800;
    }


    .metric-description {

        color: #7898bc;

        font-size: 12px;

        margin-top: 5px;
    }


    /* -------------------------------------------------------
       SECTION TITLE
    ------------------------------------------------------- */

    .section-title {

        font-size: 23px;

        font-weight: 750;

        color: white;

        margin-top: 28px;

        margin-bottom: 15px;
    }


    /* -------------------------------------------------------
       INFO CARD
    ------------------------------------------------------- */

    .info-card {

        padding: 20px;

        border-radius: 18px;

        background:
            rgba(7, 25, 51, 0.78);

        border:
            1px solid rgba(120, 185, 255, 0.12);

        margin-bottom: 18px;
    }


    .info-title {

        color: #76ddff;

        font-size: 14px;

        font-weight: 700;

        text-transform: uppercase;

        letter-spacing: 0.8px;
    }


    .info-text {

        color: #c1d5ec;

        font-size: 14px;

        line-height: 1.7;

        margin-top: 8px;
    }


    /* -------------------------------------------------------
       BUTTON
    ------------------------------------------------------- */

    .stButton > button {

        width: 100%;

        border-radius: 12px;

        border: none;

        padding: 12px 20px;

        font-weight: 700;

        font-size: 15px;

        color: white;

        background:
            linear-gradient(
                90deg,
                #009fe3,
                #0066d6
            );

        box-shadow:
            0 8px 22px rgba(0, 135, 220, 0.25);

        transition: all 0.2s ease;
    }


    .stButton > button:hover {

        transform: translateY(-2px);

        box-shadow:
            0 12px 30px rgba(0, 135, 220, 0.35);
    }


    /* -------------------------------------------------------
       DOWNLOAD BUTTON
    ------------------------------------------------------- */

    .stDownloadButton > button {

        width: 100%;

        border-radius: 12px;

        border: 1px solid rgba(100, 200, 255, 0.25);

        background:
            rgba(21, 52, 91, 0.80);

        color: white;

        font-weight: 650;
    }


    /* -------------------------------------------------------
       DATAFRAME
    ------------------------------------------------------- */

    [data-testid="stDataFrame"] {

        border-radius: 15px;

        overflow: hidden;

        border:
            1px solid rgba(100, 180, 255, 0.12);
    }


    /* -------------------------------------------------------
       FOOTER
    ------------------------------------------------------- */

    .footer {

        text-align: center;

        color: #6784a7;

        font-size: 12px;

        padding-top: 35px;

        padding-bottom: 10px;
    }

    </style>
    """,
    unsafe_allow_html=True
)


# ============================================================
# LOAD MODEL
# ============================================================

@st.cache_resource
def load_model():

    return joblib.load(
        "xgb_model.pkl"
    )


# ============================================================
# LOAD METADATA
# ============================================================

@st.cache_resource
def load_metadata():

    feature_cols = joblib.load(
        "feature_columns.pkl"
    )

    holiday_dates = joblib.load(
        "holiday_dates.pkl"
    )

    return feature_cols, holiday_dates


# ============================================================
# LOAD DATA
# ============================================================

@st.cache_data
def load_data():

    df = pd.read_excel(
        "PJMW_MW_Hourly.xlsx"
    )

    # --------------------------------------------------------
    # Rename column if necessary
    # --------------------------------------------------------

    if "Datetime" not in df.columns:

        possible_date_columns = [
            col for col in df.columns
            if "date" in col.lower()
            or "time" in col.lower()
        ]

        if possible_date_columns:

            df = df.rename(
                columns={
                    possible_date_columns[0]: "Datetime"
                }
            )

        else:

            raise ValueError(
                "Datetime column not found in dataset."
            )


    # --------------------------------------------------------
    # Target column
    # --------------------------------------------------------

    if "PJMW_MW" not in df.columns:

        possible_target_columns = [
            col for col in df.columns
            if "PJMW" in col.upper()
            or "MW" in col.upper()
        ]

        if possible_target_columns:

            df = df.rename(
                columns={
                    possible_target_columns[0]: "PJMW_MW"
                }
            )

        else:

            raise ValueError(
                "PJMW_MW target column not found."
            )


    df["Datetime"] = pd.to_datetime(
        df["Datetime"],
        errors="coerce"
    )

    df["PJMW_MW"] = pd.to_numeric(
        df["PJMW_MW"],
        errors="coerce"
    )

    df = df.dropna(
        subset=[
            "Datetime",
            "PJMW_MW"
        ]
    )

    df = (
        df
        .sort_values("Datetime")
        .reset_index(drop=True)
    )

    return df


# ============================================================
# LOAD EVERYTHING
# ============================================================

model = load_model()

feature_cols, holiday_dates = load_metadata()

df = load_data()


# ============================================================
# HERO SECTION
# ============================================================

st.markdown(
    """
    <div class="hero">

        <div class="hero-badge">
            ⚡ P679 · HOURLY ENERGY FORECASTING
        </div>

        <div class="hero-title">
            PJM Energy Intelligence
        </div>

        <div class="hero-subtitle">
            Machine learning powered electricity demand forecasting
            using a XGBoost regression model.
            Generate hourly forecasts for up to the next 30 days.
        </div>

    </div>
    """,
    unsafe_allow_html=True
)


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.markdown(
    """
    <h1 style="
        font-size:26px;
        font-weight:800;
        margin-bottom:0px;
    ">
        ⚡ Energy AI
    </h1>

    <p style="
        color:#7fa6d3;
        font-size:13px;
    ">
        PJM Demand Forecasting System
    </p>
    """,
    unsafe_allow_html=True
)


st.sidebar.markdown("---")


st.sidebar.markdown(
    "### 🎯 Forecast Settings"
)


forecast_days = st.sidebar.slider(
    "Forecast Horizon",
    min_value=1,
    max_value=30,
    value=30,
    step=1
)


st.sidebar.markdown(
    f"""
    <div style="
        padding:12px;
        border-radius:12px;
        background:rgba(20,55,95,0.55);
        margin-top:8px;
    ">
        <span style="
            color:#86acd8;
            font-size:12px;
        ">
            SELECTED HORIZON
        </span>

        <br>

        <span style="
            color:white;
            font-size:22px;
            font-weight:800;
        ">
            {forecast_days} Days
        </span>

        <br>

        <span style="
            color:#7696ba;
            font-size:12px;
        ">
            {forecast_days * 24} hourly predictions
        </span>
    </div>
    """,
    unsafe_allow_html=True
)


st.sidebar.markdown("---")


st.sidebar.markdown(
    """
    ### 🤖 Model

    **XGBoost Regressor**

    The selected model uses:

    • Historical lag demand
    • Daily and weekly seasonality
    • Calendar information
    • Holiday information
    • Rolling demand statistics
    """,
)


st.sidebar.markdown("---")


st.sidebar.markdown(
    """
    ### 📊 Forecasting

    **Frequency:** Hourly
    **Target:** PJMW_MW
    **Maximum Horizon:** 30 days
    **Model Type:** Regression
    """
)


# ============================================================
# DASHBOARD METRICS
# ============================================================

latest_value = df["PJMW_MW"].iloc[-1]

average_value = df["PJMW_MW"].mean()

peak_value = df["PJMW_MW"].max()

latest_timestamp = df["Datetime"].iloc[-1]


col1, col2, col3, col4 = st.columns(4)


with col1:

    st.markdown(
        f"""
        <div class="metric-card">

            <div class="metric-label">
                Current Demand
            </div>

            <div class="metric-value">
                {latest_value:,.0f} MW
            </div>

            <div class="metric-description">
                Latest observed consumption
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


with col2:

    st.markdown(
        f"""
        <div class="metric-card">

            <div class="metric-label">
                Historical Average
            </div>

            <div class="metric-value">
                {average_value:,.0f} MW
            </div>

            <div class="metric-description">
                Complete dataset average
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


with col3:

    st.markdown(
        f"""
        <div class="metric-card">

            <div class="metric-label">
                Peak Demand
            </div>

            <div class="metric-value">
                {peak_value:,.0f} MW
            </div>

            <div class="metric-description">
                Maximum recorded demand
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


with col4:

    st.markdown(
        f"""
        <div class="metric-card">

            <div class="metric-label">
                Last Updated
            </div>

            <div class="metric-value">
                {latest_timestamp.strftime("%d %b %Y")}
            </div>

            <div class="metric-description">
                {latest_timestamp.strftime("%H:%M")} hourly observation
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


# ============================================================
# HISTORICAL OVERVIEW
# ============================================================

st.markdown(
    '<div class="section-title">📈 Historical Demand Overview</div>',
    unsafe_allow_html=True
)


history_chart = df.tail(24 * 7)


fig_history, ax_history = plt.subplots(
    figsize=(14, 5)
)

fig_history.patch.set_alpha(0)

ax_history.set_facecolor(
    "#071a33"
)

ax_history.plot(
    history_chart["Datetime"],
    history_chart["PJMW_MW"],
    linewidth=2.0,
    label="Historical Demand"
)

ax_history.set_xlabel(
    "Datetime",
    color="white"
)

ax_history.set_ylabel(
    "Demand (MW)",
    color="white"
)

ax_history.set_title(
    "Last 7 Days of Observed Electricity Demand",
    color="white",
    fontsize=15,
    fontweight="bold"
)

ax_history.tick_params(
    colors="white"
)

for spine in ax_history.spines.values():

    spine.set_alpha(0.15)

ax_history.grid(
    alpha=0.10
)

ax_history.legend(
    facecolor="#0a2444",
    labelcolor="white"
)

fig_history.autofmt_xdate()

st.pyplot(
    fig_history,
    use_container_width=True
)

plt.close(fig_history)


# ============================================================
# FEATURE ENGINEERING
# ============================================================

def create_features(history):

    current_time = (
        history["Datetime"].iloc[-1]
        + timedelta(hours=1)
    )

    row = {}

    # --------------------------------------------------------
    # Calendar variables
    # --------------------------------------------------------

    row["Hour"] = current_time.hour

    row["Day"] = current_time.day

    row["DayOfWeek"] = current_time.dayofweek

    row["Month"] = current_time.month

    row["Year"] = current_time.year

    row["IsWeekend"] = int(
        current_time.dayofweek in [5, 6]
    )

    row["IsHoliday"] = int(
        current_time.date() in holiday_dates
    )


    # --------------------------------------------------------
    # Lag variables
    # --------------------------------------------------------

    row["lag_1"] = (
        history["PJMW_MW"].iloc[-1]
    )

    row["lag_2"] = (
        history["PJMW_MW"].iloc[-2]
    )

    row["lag_3"] = (
        history["PJMW_MW"].iloc[-3]
    )

    row["lag_24"] = (
        history["PJMW_MW"].iloc[-24]
    )

    row["lag_48"] = (
        history["PJMW_MW"].iloc[-48]
    )

    row["lag_168"] = (
        history["PJMW_MW"].iloc[-168]
    )


    # --------------------------------------------------------
    # Rolling statistics
    # --------------------------------------------------------

    row["rolling_mean_24"] = (
        history["PJMW_MW"]
        .iloc[-24:]
        .mean()
    )

    row["rolling_mean_168"] = (
        history["PJMW_MW"]
        .iloc[-168:]
        .mean()
    )

    row["rolling_std_24"] = (
        history["PJMW_MW"]
        .iloc[-24:]
        .std()
    )


    return (
        pd.DataFrame([row]),
        current_time
    )


# ============================================================
# FORECAST FUNCTION
# ============================================================

def generate_forecast(
    historical_df,
    number_of_days
):

    history = historical_df[
        [
            "Datetime",
            "PJMW_MW"
        ]
    ].copy()

    predictions = []

    total_hours = (
        number_of_days * 24
    )


    for _ in range(total_hours):

        X_future, timestamp = (
            create_features(history)
        )


        # ----------------------------------------------------
        # Check expected columns
        # ----------------------------------------------------

        missing_columns = [
            col
            for col in feature_cols
            if col not in X_future.columns
        ]


        if missing_columns:

            raise ValueError(
                "Missing model features: "
                + str(missing_columns)
            )


        # ----------------------------------------------------
        # XGBoost prediction
        # ----------------------------------------------------

        prediction = model.predict(
            X_future[
                feature_cols
            ]
        )[0]


        # ----------------------------------------------------
        # Prevent impossible negative demand
        # ----------------------------------------------------

        prediction = max(
            0,
            float(prediction)
        )


        predictions.append(
            {
                "Datetime": timestamp,
                "Forecast_MW": prediction
            }
        )


        # ----------------------------------------------------
        # Add prediction to history
        # ----------------------------------------------------

        new_row = pd.DataFrame(
            {
                "Datetime": [
                    timestamp
                ],

                "PJMW_MW": [
                    prediction
                ]
            }
        )


        history = pd.concat(
            [
                history,
                new_row
            ],
            ignore_index=True
        )


    return pd.DataFrame(
        predictions
    )


# ============================================================
# FORECAST BUTTON
# ============================================================

st.markdown(
    '<div class="section-title">🔮 Generate Future Forecast</div>',
    unsafe_allow_html=True
)


st.markdown(
    """
    <div class="info-card">

        <div class="info-title">
            Forecast Engine
        </div>

        <div class="info-text">
            The XGBoost model generates hourly predictions
            recursively. Each predicted demand value becomes part
            of the historical sequence used to generate subsequent
            lag and rolling features.
        </div>

    </div>
    """,
    unsafe_allow_html=True
)


generate = st.button(
    "⚡ Generate Energy Forecast"
)


if generate:

    with st.spinner(
        "Generating hourly energy demand forecast..."
    ):

        forecast_df = generate_forecast(
            df,
            forecast_days
        )


    # Store in session
    st.session_state[
        "forecast_df"
    ] = forecast_df


# ============================================================
# SHOW FORECAST
# ============================================================

if "forecast_df" in st.session_state:

    forecast_df = (
        st.session_state[
            "forecast_df"
        ]
    )


    # ========================================================
    # FORECAST METRICS
    # ========================================================

    avg_forecast = (
        forecast_df[
            "Forecast_MW"
        ].mean()
    )

    max_forecast = (
        forecast_df[
            "Forecast_MW"
        ].max()
    )

    min_forecast = (
        forecast_df[
            "Forecast_MW"
        ].min()
    )


    peak_time = (
        forecast_df.loc[
            forecast_df[
                "Forecast_MW"
            ].idxmax(),
            "Datetime"
        ]
    )


    st.markdown(
        '<div class="section-title">📊 Forecast Summary</div>',
        unsafe_allow_html=True
    )


    fc1, fc2, fc3, fc4 = st.columns(4)


    with fc1:

        st.markdown(
            f"""
            <div class="metric-card">

                <div class="metric-label">
                    Average Forecast
                </div>

                <div class="metric-value">
                    {avg_forecast:,.0f} MW
                </div>

                <div class="metric-description">
                    Expected average demand
                </div>

            </div>
            """,
            unsafe_allow_html=True
        )


    with fc2:

        st.markdown(
            f"""
            <div class="metric-card">

                <div class="metric-label">
                    Forecast Peak
                </div>

                <div class="metric-value">
                    {max_forecast:,.0f} MW
                </div>

                <div class="metric-description">
                    Highest predicted demand
                </div>

            </div>
            """,
            unsafe_allow_html=True
        )


    with fc3:

        st.markdown(
            f"""
            <div class="metric-card">

                <div class="metric-label">
                    Forecast Minimum
                </div>

                <div class="metric-value">
                    {min_forecast:,.0f} MW
                </div>

                <div class="metric-description">
                    Lowest predicted demand
                </div>

            </div>
            """,
            unsafe_allow_html=True
        )


    with fc4:

        st.markdown(
            f"""
            <div class="metric-card">

                <div class="metric-label">
                    Peak Expected
                </div>

                <div class="metric-value">
                    {peak_time.strftime("%d %b")}
                </div>

                <div class="metric-description">
                    At {peak_time.strftime("%H:%M")}
                </div>

            </div>
            """,
            unsafe_allow_html=True
        )


    # ========================================================
    # FORECAST CHART
    # ========================================================

    st.markdown(
        '<div class="section-title">⚡ Historical vs Forecast Demand</div>',
        unsafe_allow_html=True
    )


    recent_history = df.tail(
        24 * 7
    )


    fig, ax = plt.subplots(
        figsize=(15, 6)
    )

    fig.patch.set_alpha(0)

    ax.set_facecolor(
        "#071a33"
    )


    # Historical
    ax.plot(
        recent_history[
            "Datetime"
        ],
        recent_history[
            "PJMW_MW"
        ],
        linewidth=2.2,
        label="Historical"
    )


    # Forecast
    ax.plot(
        forecast_df[
            "Datetime"
        ],
        forecast_df[
            "Forecast_MW"
        ],
        linewidth=2.4,
        linestyle="--",
        label="XGBoost Forecast"
    )


    ax.axvline(
        recent_history[
            "Datetime"
        ].iloc[-1],
        linestyle=":",
        linewidth=1.5,
        label="Forecast Start"
    )


    ax.set_xlabel(
        "Datetime",
        color="white"
    )

    ax.set_ylabel(
        "Demand (MW)",
        color="white"
    )

    ax.set_title(
        "PJM Electricity Demand Forecast",
        color="white",
        fontsize=17,
        fontweight="bold"
    )


    ax.tick_params(
        colors="white"
    )


    ax.grid(
        alpha=0.10
    )


    ax.legend(
        facecolor="#0a2444",
        labelcolor="white"
    )


    for spine in ax.spines.values():

        spine.set_alpha(0.15)


    fig.autofmt_xdate()


    st.pyplot(
        fig,
        use_container_width=True
    )

    plt.close(fig)


    # ========================================================
    # FORECAST TABLE
    # ========================================================

    st.markdown(
        '<div class="section-title">📋 Hourly Forecast Data</div>',
        unsafe_allow_html=True
    )


    display_forecast = (
        forecast_df
        .copy()
    )


    display_forecast[
        "Datetime"
    ] = display_forecast[
        "Datetime"
    ].dt.strftime(
        "%d-%b-%Y %H:%M"
    )


    display_forecast[
        "Forecast_MW"
    ] = display_forecast[
        "Forecast_MW"
    ].round(2)


    st.dataframe(
        display_forecast,
        use_container_width=True,
        height=430
    )


    # ========================================================
    # DOWNLOAD
    # ========================================================

    st.markdown(
        '<div class="section-title">⬇️ Export Forecast</div>',
        unsafe_allow_html=True
    )


    csv = forecast_df.to_csv(
        index=False
    )


    download_col1, download_col2 = (
        st.columns([2, 1])
    )


    with download_col1:

        st.download_button(
            label="⬇️ Download Forecast CSV",
            data=csv,
            file_name=(
                f"pjm_{forecast_days}_day_forecast.csv"
            ),
            mime="text/csv"
        )


    with download_col2:

        st.success(
            f"{len(forecast_df):,} hourly records"
        )


# ============================================================
# MODEL INFORMATION
# ============================================================

st.markdown(
    '<div class="section-title">🤖 Model Information</div>',
    unsafe_allow_html=True
)


info1, info2 = st.columns(2)


with info1:

    st.markdown(
        """
        <div class="info-card">

            <div class="info-title">
                Selected Model
            </div>

            <div class="info-text">

                <b style="color:white;">
                XGBoost Regressor
                </b>

                <br><br>

                The model uses historical demand,
                lag variables, calendar variables,
                holiday indicators and rolling
                statistics to predict electricity
                consumption.

            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


with info2:

    st.markdown(
        """
        <div class="info-card">

            <div class="info-title">
                Forecast Method
            </div>

            <div class="info-text">

                <b style="color:white;">
                Recursive Multi-Step Forecasting
                </b>

                <br><br>

                Each generated hourly prediction is
                added to the historical sequence and
                becomes an input for the next prediction.

            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


# ============================================================
# DATASET INFORMATION
# ============================================================

st.markdown(
    '<div class="section-title">🗂️ Dataset Information</div>',
    unsafe_allow_html=True
)


dataset_col1, dataset_col2, dataset_col3 = st.columns(3)


with dataset_col1:

    st.markdown(
        f"""
        <div class="metric-card">

            <div class="metric-label">
                Observations
            </div>

            <div class="metric-value">
                {len(df):,}
            </div>

            <div class="metric-description">
                Hourly records
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


with dataset_col2:

    st.markdown(
        f"""
        <div class="metric-card">

            <div class="metric-label">
                Data Start
            </div>

            <div class="metric-value">
                {df["Datetime"].min().strftime("%Y")}
            </div>

            <div class="metric-description">
                Historical coverage
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


with dataset_col3:

    st.markdown(
        f"""
        <div class="metric-card">

            <div class="metric-label">
                Data End
            </div>

            <div class="metric-value">
                {df["Datetime"].max().strftime("%Y")}
            </div>

            <div class="metric-description">
                Latest historical observation
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


# ============================================================
# FOOTER
# ============================================================

st.markdown(
    """
    <div class="footer">

        ⚡ P679 Hourly Energy Consumption Forecasting

        <br>

        XGBoost Regression · Time Series Forecasting

        <br><br>

        Built with Python · Pandas · Scikit-learn · Streamlit

    </div>
    """,
    unsafe_allow_html=True
)